<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1


Subsetting: Selecting elements from a given list/array

Indexing: Selecting *only ONE* element

Slicing: Selecting *multiple elements* 

Masking: A type of subsetting where selection of an array is done by a True/False basis

## Exercise 2

In [3]:
import numpy as np

In [4]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [5]:
np_array_int = np_array_2d [:,0] # ':' means start to end

In [6]:
np_array_int #gives string output of numbers

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [7]:
np_array_int.astype(int) #converts type to integer (int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [8]:
mask = (np_array_int.astype(int) % 2 != 0)

In [9]:
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [10]:
np_array_str = np_array_2d[mask,1]

In [11]:
np_array_str

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [12]:
x=[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

In [13]:
x_array=np.array(x)

In [14]:
mask_51 = (x_array > 50)
mask_49 = (x_array < 50)
mask_50 = (x_array == 50)

In [15]:
x_array[mask_51]=1
x_array[mask_49]=-1
x_array[mask_50]=0

In [16]:
x_array #LETS GOOOO

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])