<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**List**

In [2]:
#Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy arrays**

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**DIctionary**

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [9]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] #0,1,2 or -1,-2,-3
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"] 

In [6]:
py_real_names[0]

'Natasha Romanoff'

In [7]:
py_real_names[-1]

'Stephen Strange'

## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}



## 1.4 Higher dimensional lists

In [12]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

In [13]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [14]:
np_array_2d = np.array(py_list_2d)

## 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [16]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [17]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [20]:
len(np_array_2d) #len=length

10

In [ ]:
np_array_2d.size #size=total elements

20

In [24]:
np_array_2d.shape #shape=(column,row)

(10, 2)

## 2.2 Arrays are fussy about type

In [25]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

## 2.3 Adding a number

In [26]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [27]:
np_array

array([1, 2, 3, 4, 5])

In [34]:
np_array + 100

array([101, 102, 103, 104, 105])

In [35]:
np_array + [100]

array([101, 102, 103, 104, 105])

## 2.4 Adding another list

In [38]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(np_array_1, np_array_2, sep='\n')

[1 2 3 4 5]
[10 20 30 40 50]


## 2.5 Multiplying by a Number

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [37]:
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

In [39]:
py_list

[1, 2, 3, 4, 5]

In [40]:
np_array

array([1, 2, 3, 4, 5])

## 2.6 Squaring

In [3]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [2]:
import numpy as np

## 2.7 Asking questions

## 2.8 Mathematics

## Footnotes