<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [21]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**List**

In [2]:
#Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy arrays**

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**DIctionary**

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [23]:
racists_in_TMJC = ['Runduo, Tian Yu, Jaeden, Javen, Zhi Heng, Erfan, Mr Light']

In [9]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] #0,1,2 or -1,-2,-3
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"] 

In [6]:
py_real_names[0]

'Natasha Romanoff'

In [7]:
py_real_names[-1]

'Stephen Strange'

## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}



## 1.4 Higher dimensional lists

In [12]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

In [25]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [26]:
np_array_2d = np.array(py_list_2d)

In [27]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [28]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

## 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [16]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [17]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [20]:
len(np_array_2d) #len=length

10

In [ ]:
np_array_2d.size #size=total elements

20

In [24]:
np_array_2d.shape #shape=(column,row)

(10, 2)

## 2.2 Arrays are fussy about type

In [25]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

## 2.3 Adding a number

In [3]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [4]:
np_array + 10

array([11, 12, 13, 14, 15])

In [5]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [2]:
import numpy as np

## 2.4 Adding another list

In [6]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [7]:
py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a number

In [9]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [10]:
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

In [11]:
np_array*2

array([ 2,  4,  6,  8, 10])

In [12]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

## 2.6 Squaring

In [29]:
import numpy as np

In [30]:
py_list=[1,2,3,4]

In [31]:
np_array=np.array(py_list)

In [32]:
py_list*py_list

TypeError: can't multiply sequence by non-int of type 'list'

In [33]:
np_array*np_array

array([ 1,  4,  9, 16])

In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [14]:
py_list == 3     # Works, but what IS the question?
np_array == 3  
np_array > 3  

array([False, False, False,  True,  True])

In [16]:
py_list == 3 #3 is a subset of py_list

False

In [17]:
np_array == 3

array([False, False,  True, False, False])

In [18]:
np_array > 3

array([False, False, False,  True,  True])

## 2.7 Asking questions

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [ ]:
py_list == 3 #considers list itself

False

In [22]:
np_array == 3 #considers elements of array

array([False, False,  True, False, False])

In [24]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [26]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

In [12]:
fruit = ['Apple','orange','banana']
print(dir(fruit))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [2]:
print(fruit)

['Apple', 'orange', 'banana']


In [3]:
print(fruit[1])

orange


In [4]:
print(fruit[0:1])

['Apple']


In [13]:
print(fruit[0:3:1])
print(dir(fruit))

['Apple', 'orange', 'banana']
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
for x in fruits:
    print(x)

In [14]:
fruit [0]='pineapple'

In [15]:
print(fruit)

['pineapple', 'orange', 'banana']
